/* Generated by Yosys 0.19+36 (git sha1 30a4218f537, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_gc(clk, enable, reset, gray_count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  input clk;
  wire clk;
  wire [7:0] count;
  input enable;
  wire enable;
  output [7:0] gray_count;
  wire [7:0] gray_count;
  input reset;
  wire reset;
  sky130_fd_sc_hd__xor2_1 _24_ (
    .A(count[1]),
    .B(count[0]),
    .X(gray_count[0])
  );
  sky130_fd_sc_hd__xor2_1 _25_ (
    .A(count[2]),
    .B(count[1]),
    .X(gray_count[1])
  );
  sky130_fd_sc_hd__xor2_1 _26_ (
    .A(count[3]),
    .B(count[2]),
    .X(gray_count[2])
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(count[4]),
    .B(count[3]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__and2_0 _28_ (
    .A(count[4]),
    .B(count[3]),
    .X(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(_08_),
    .B(_09_),
    .Y(gray_count[3])
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(count[5]),
    .B(count[4]),
    .X(gray_count[4])
  );
  sky130_fd_sc_hd__xor2_1 _31_ (
    .A(count[6]),
    .B(count[5]),
    .X(gray_count[5])
  );
  sky130_fd_sc_hd__nor2_1 _32_ (
    .A(count[7]),
    .B(count[6]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and2_0 _33_ (
    .A(count[7]),
    .B(count[6]),
    .X(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(_10_),
    .B(_11_),
    .Y(gray_count[6])
  );
  sky130_fd_sc_hd__o21bai_1 _35_ (
    .A1(enable),
    .A2(count[0]),
    .B1_N(reset),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _36_ (
    .A1(enable),
    .A2(count[0]),
    .B1(_12_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__and3_1 _37_ (
    .A(enable),
    .B(count[1]),
    .C(count[0]),
    .X(_13_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(enable),
    .A2(count[0]),
    .B1(count[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _39_ (
    .A(reset),
    .B(_13_),
    .C(_14_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(count[2]),
    .B(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__and4_1 _41_ (
    .A(enable),
    .B(count[2]),
    .C(count[1]),
    .D(count[0]),
    .X(_16_)
  );
  sky130_fd_sc_hd__nor3_1 _42_ (
    .A(reset),
    .B(_15_),
    .C(_16_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21bai_1 _43_ (
    .A1(count[3]),
    .A2(_16_),
    .B1_N(reset),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _44_ (
    .A1(count[3]),
    .A2(_16_),
    .B1(_17_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(count[3]),
    .A2(_16_),
    .B1(count[4]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a211oi_1 _46_ (
    .A1(_09_),
    .A2(_16_),
    .B1(_18_),
    .C1(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and3_1 _47_ (
    .A(count[5]),
    .B(_09_),
    .C(_16_),
    .X(_19_)
  );
  sky130_fd_sc_hd__a21oi_1 _48_ (
    .A1(_09_),
    .A2(_16_),
    .B1(count[5]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor3_1 _49_ (
    .A(reset),
    .B(_19_),
    .C(_20_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a31oi_1 _50_ (
    .A1(count[5]),
    .A2(_09_),
    .A3(_16_),
    .B1(count[6]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__and4_1 _51_ (
    .A(count[6]),
    .B(count[5]),
    .C(_09_),
    .D(_16_),
    .X(_22_)
  );
  sky130_fd_sc_hd__nor3_1 _52_ (
    .A(reset),
    .B(_21_),
    .C(_22_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a41oi_1 _53_ (
    .A1(count[5]),
    .A2(_09_),
    .A3(_11_),
    .A4(_16_),
    .B1(reset),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o21a_1 _54_ (
    .A1(count[7]),
    .A2(_22_),
    .B1(_23_),
    .X(_07_)
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _58_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _59_ (
    .CLK(clk),
    .D(_04_),
    .Q(count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _60_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _61_ (
    .CLK(clk),
    .D(_06_),
    .Q(count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _62_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[7])
  );
  assign gray_count[7] = count[7];
endmodule
